[package]
name = "prompt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#termcolor = "1.3"
colored = { path = "/Users/Gorilskij/code/rust/colored" }
#snailquote = "0.3.1"